### ISSUE TITLE
compiling on raspberry pi

### ISSUE THREAD

**Issue by lyonrt** [myzinsky/CloudLogCatQt#2]
What are the steps to config on a raspberry pi?  Thanks!

**Comment by myzinsky** [comment]
I think the same as on any other Linux system. Best ist to install qtcreator, load the project and press play to compile and run it.

Alternately just install qmake and qt dependencies and build it by 

qmake *.pro
make

**Comment by Vic152** [comment]
I just made it compile on rPi following the instruction in Github.
