### ISSUE TITLE
Application does not save settings

### ISSUE THREAD

**Issue by Axon07** [myzinsky/CloudLogCatQt#5]
I have just compiled the application in Windows 10 but after launching it I cannot save any settings. 
After entering the correct settings I checked cloudlog and it has not updated any information

the URL I used was https://URL/index.php/api/radio with the URL being the domain of my server. Confirmed that the API key is read/write.

Is there a settings file that should be created when the settings are saved?

**Comment by Axon07** [comment]
Also when I add my settings in manually into the .cpp file then run it I get the following error:

qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed

**Comment by myzinsky** [comment]
Seams that the link is wrong, its just:

your.cloudlog.server.com

and the key

**Comment by Axon07** [comment]
Just added the server info without the https:// or anything else and the error went away but still will not connect with CloudLog server.

Also I looked into the code and it looks like it should create a settings.ini file which it does not.

**Comment by myzinsky** [comment]
So the settings is encapsulated within Qt. So actually Qt will take care about this. I'm not sure if on windows it will also create an ini file. I thing its even storing the information in the registry. 

I think there is no way out, that I build it also on windows. Have you used windows 10?

**Comment by Axon07** [comment]
Also got" unused parameter 'event'" on line 83 and "'append' is deprecated: Use QString's toUtf8(), toLatin1() or toLocal8Bit()" on line 185


What version of Qt did you compile it with in Windows? Noticed in another issue that you used version 5 and not 6 so I compiled it in 5.15.2 which is maybe why I am having so many issues.

**Comment by Axon07** [comment]
Yes I am using Windows 10 at the moment.

**Comment by myzinsky** [comment]
So far I just support Qt5. Qt6 is on the roadmap.

**Comment by Axon07** [comment]
Any specific Qt 5 version?

**Comment by myzinsky** [comment]
So I assume that i dont use the settings environment correctly such that it akes problems on windows?

**Comment by dl6nm** [comment]
As described in the pull request #12, it seems like a change of the QSettings::Format solves this problem.
